name: course_rep_management_panel
description: An admin dashboard for managing course representatives for a university campus
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.5.1
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.6.2
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
